src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Cocur\Slugify;
use Cocur\Slugify\Slugify as SlugifySlugify;
use Faker\Provider\cs_CZ\DateTime;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @ORM\Table(name="Properties")
 * @Vich\Uploadable()
 */
class Property
{
    const HEAT = [
        0 => 'Electric',
        1 => 'Gas',
        2 => 'Hybrid'
    ];

    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->options = new ArrayCollection();
    }

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="This field cannot be blank.")
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Assert\NotBlank(message="This description cannot be blank.")
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(
     *  min=10,
     *  max=400,
     *  minMessage="The surface must be greater than or equal to 10.",
     *  maxMessage="The surface must less than or equal to 400.")
     * @Assert\NotBlank(message="This field cannot be blank.")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(
     *  min=2,
     *  max=10,
     *  minMessage="The number rooms must be greater than or equal to 1.",
     *  maxMessage="The number rooms must less than or equal to 6.")
     * @Assert\NotBlank(message="This field cannot be blank.")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(
     *  min=2,
     *  max=10,
     *  minMessage="The number of bedrooms must be greater than or equal to 1.",
     *  maxMessage="The number of bedrooms must less than or equal to 10.")
     * @Assert\NotBlank(message="This field cannot be blank.")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(
     *  min=0,
     *  max=15,
     *  minMessage="The floor must be greater than or equal to 1.",
     *  maxMessage="The floor must less than or equal to 10.")
     * @Assert\NotBlank(message="This field cannot be blank.")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(
     *  min=10000,
     *  max=1000000,
     *   minMessage="The price must be greater than or equal to 1000.",
     *   maxMessage="The price must less than or equal to 10 000.")
     * @Assert\NotBlank(message="This field cannot be blank.")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="This field cannot be blank.")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="This field cannot be blank.")
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="This field cannot be blank.")
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="This field cannot be blank.")
     */
    private $postalCode;

    /**
     * @ORM\Column(type="boolean",options={"default":false})
     */
    private $sold = false;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255,nullable=true) 
     */
    private $fileName;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="property_image",fileNameProperty="fileName")
     * @Assert\File(maxSize="8M",
     *     mimeTypes={
     *     "image/jpeg",
     *     "image/jpg"},
     *     mimeTypesMessage = "Please upload a valid image file (jpeg or jpg)"
     * )
     */
    private $imageFile;


    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
     */
    private $options;

    /**
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * @return string
     */
    public function getSlug(): string
    {
        return (new SlugifySlugify())->slugify($this->title);
    }

    /**
     * @param string $title
     */
    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return string
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * @param string $description
     */
    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return int
     */
    public function getSurface(): ?int
    {
        return $this->surface;
    }

    /**
     * @param $surface
     */
    public function setSurface(?int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    /**
     * @return int
     */
    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    /**
     * @param int $rooms
     */
    public function setRooms(?int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return int
     */
    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    /**
     * @param int $bedrooms
     */
    public function setBedrooms(?int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    /**
     * @return int
     */
    public function getFloor(): ?int
    {
        return $this->floor;
    }

    /**
     * @param int $floor
     */
    public function setFloor(?int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    /**
     * @return int
     */
    public function getPrice(): ?int
    {
        return $this->price;
    }

    /**
     * @return strinf
     */
    public function getFormatedPrice()
    {
        return number_format($this->price, 0, '', ' ');
    }

    /**
     * @param int $price
     */
    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    /**
     * @return int
     */
    public function getHeat(): ?int
    {
        return $this->heat;
    }

    /**
     * @return string
     */
    public function getHeatType(): ?string
    {
        return self::HEAT[$this->heat];
    }

    /**
     * @param int $heat
     */
    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    /**
     * @return string
     */
    public function getCity(): ?string
    {
        return $this->city;
    }


    /**
     * @param string $city
     */
    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return string
     */
    public function getAdress(): ?string
    {
        return $this->adress;
    }

    /**
     * @param string $adress
     */
    public function setAdress(?string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    /**
     * @return string
     */
    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    /**
     * @param string $postalCode
     */
    public function setPostalCode(?string $postalCode): self
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    /**
     * @return bool
     */
    public function getSold(): ?bool
    {
        return $this->sold;
    }

    /**
     * @param bool $sold
     */
    public function setSold(?bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    /**
     * @return string
     */
    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    /**
     * @param null|string $fileName
     */
    public function setFileName(?string $fileName): self
    {
        $this->fileName = $fileName;

        return $this;
    }

    /**
     * @return File
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File $imageFile
     */
    public function setImageFile(?File $imageFile): self
    {
        $this->imageFile = $imageFile;
        if($this->imageFile instanceof UploadedFile){
            $this->updatedAt = new \DateTime('now');
        }

        return $this;
    }


    /**
     * @return DateTimeInterface
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTimeInterface $createdAt
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return DateTimeInterface
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTimeInterface $createdAt
     */
    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {

src/Controller/FrontOffice/HomeController.php
<?php

namespace App\Controller\FrontOffice;

use App\Repository\PropertyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
/**
 * Class HomeController
 */
class HomeController extends AbstractController
{
    /**
     * @param PropertyRepository $propertyRepository
     * @return Response
     * @Route("/", name="home")
     */
    public function index(PropertyRepository $propertyRepository): Response
    {
        $properties = $propertyRepository->findAllLatest();

        return $this->render('front_office/home.html.twig',compact('properties'));
    }

    /**
     * @return Response
     * @Route("/change-locale/{locale}",name="change_locale")
     */
    public function changeLocale($locale,Request $request):Response
    {
        $request->getSession()->set('_locale',$locale);
        
        return $this->redirect($request->headers->get('referer'));
    }
}

src/Controller/FrontOffice/PropertyController.php
<?php

namespace App\Controller\FrontOffice;

use App\Entity\Contact;
use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Form\ContactType;
use App\Notification\ContactNotification;
use App\Repository\PropertyRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

class PropertyController extends AbstractController
{
    /**
     * @return Response
     * @param PropertyRepository $propertyRepository
     * 
     * @Route("/properties", name="property.index")
     */
    public function index(PropertyRepository $propertyRepository,Request $request, PaginatorInterface $paginator): Response
    {
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class,$search);

        $form->handleRequest($request);


        $properties = $paginator->paginate(
            $propertyRepository->findAllVisibleQuery($search),
            $request->query->getInt('page',1),
            $this->getParameter('max_properties_per_page')
        );

        return $this->render('front_office/property/index.html.twig',[
            'current_menu_buy'=>'buy',
            'properties' => $properties ,
            'searchForm'=> $form->createView() 
        ]);
    }

    /**
     * @param string $slug
     * @param Property $property
     * @param PropertyRepository $propertyRepository
     * @param Request $request
     * @param TranslatorInterface $translator
     * @param ContactNotification $notification
     * 
     * @return Response
     * 
     * @Route("/properties/{slug}-{id}", name="property.show",requirements={"slug":"[a-z0-9\-]*"})
     */
    public function show(Property $property,string $slug,PropertyRepository $propertyRepository,Request $request,
    TranslatorInterface $translator,ContactNotification $notification): Response
    {
        
        if($property->getSlug() !== $slug ){
            return $this->redirectToRoute('property.show',[
                'id' => $property->getId(),
                'slug'=>$property->getSlug()
            ],301);
        }

        $contact = new Contact();
        $contact->setProperty($property);

        $form = $this->createForm(ContactType::class,$contact);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $notification->notify($contact);

            $message = 'Your e-mail has been sent';
            $translator->trans($message);

            $this->addFlash('success',$message);

            /*return $this->redirectToRoute('property.show',[
                'id' => $property->getId(),
                'slug'=>$property->getSlug()
            ]);*/
        }


        return $this->render('front_office/property/show.html.twig',[
            'current_menu'=>'properties',
            'property'=>$property,
            'contactForm'=>$form->createView()
        ]);
    }
}

src/Controller/FrontOffice/SecurityController.php
<?php

namespace App\Controller\FrontOffice;


use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Entity\User;
use App\Form\PropertySearchType;
use App\Form\ContactType;
use App\Notification\ContactNotification;
use App\Repository\PropertyRepository;
use App\Repository\UserRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Contracts\Translation\TranslatorInterface;

class SecurityController extends AbstractController
{
    /**
     * @return Response
     * @param PropertyRepository $propertyRepository
     * 
     * @Route("/login", name="login")
     */
    public function login(AuthenticationUtils $authenticationUtils,Request $request): Response
    {
        if ($this->getUser()) {
            $this->addFlash('error','Already logged in!');
           return $this->redirectToRoute('home');
        }

        $error = $authenticationUtils->getLastAuthenticationError();
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('front_office/security/login.html.twig',[
            'error'=>$error,
            'lastUsername'=>$lastUsername,
            'current_menu'=>'login'
        ]);
    }

     /**
     * @Route("/logout", name="logout",methods="POST|GET")
     */
    public function logout()
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
}

templates/front_office/property/_property.html.twig
 <div class="card mb-4">
	<div class="card-header">
		{% if property.fileName %}
			<a href=" {{path('property.show',{ id:property.id, slug : property.slug}) }} ">
				<img src="{{vich_uploader_asset(property,'imageFile') | imagine_filter("thumb") }}" alt="card-img-top"/>
			</a>
		{% else %}
			<a href=" {{path('property.show',{ id:property.id, slug : property.slug}) }} ">
				<img src="{{'/images/properties/empty.jpg' | imagine_filter("thumb") }}" alt="card-img-top"/>
			</a>
		{% endif %}
	</div>
	<div class="card-body">
		<h5 class="card-title">
			<a href=" {{path('property.show',{ id:property.id, slug : property.slug}) }} ">
				{{property.title}}
			</a>
		</h5>
		<p class="card-text">{{property.description | nl2br}}
			({{property.postalCode}})
		</p>
		<p class="card-text">{{property.surface}} m² - {{property.city}}
			({{property.postalCode}})
		</p>
		<div class="text-primary font-weight-bold" style="font-size:2.5rem">
			{{property.formatedPrice}} €
		</div>
	</div>
</div>

templates/front_office/property/index.html.twig
{% extends "/layouts/base.html.twig" %}
{% block title 'See all our availables properties'%}

{% block body %}
   
    <div class="jumbotron">
        <div class="container">
            {{ form_start(searchForm) }}
            <div class="form-row">
                <div class="col-md-4">
                    <div class="form-group">
                    {{ form_row(searchForm.minSurface) }}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                    {{ form_row(searchForm.maxPrice) }}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                    {{ form_row(searchForm.options) }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 mx-auto">
                    <div class="form-group">
                        <button class="btn btn-primary">{% trans %} Search {% endtrans %}</button>
                    </div>
                </div>
            </div>
            {{ form_end(searchForm) }}
        </div>
    </div> 

    <div class="container">
        <h1 class="text-center"> {% trans %} See all our properties {% endtrans %}</h1>
        
        <div class="row">
            {% for property in properties %}
                <div class="col-md-4">
                    {% include "front_office/property/_property.html.twig" %}
                </div>
            {% else %}
                <h1 class="text-center mt-4"> {% trans %} No properties found corresponding to your search criteria {% endtrans %}</h1>
            {% endfor %}
        </div>
        <div class="row">
            <div class="col-md-6 mx-auto mt-4">
                {{ knp_pagination_render(properties) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/front_office/property/show.html.twig
{% extends "/layouts/base.html.twig" %}
{% block title 'Property '~ property.id ~' details'%}

{% block body %}

    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-8" style="overflow: hidden;">
                    {% if property.fileName %}
                        <img src="{{vich_uploader_asset(property,'imageFile') | imagine_filter("medium") }}" alt="card-img-top"/>
                    {% else %}
                        <img src="{{'/images/properties/empty.jpg' | imagine_filter("medium") }}" alt="card-img-top"/>
                    {% endif %}
                </div>
                <div class="col-md-4">
                    <h1>
                        {{ property.title }}
                    </h1>
                    <h2>
                        {{ property.rooms }}
                        -
                        {{ property.surface }}
                        m²</h2>
                    <div class="text-primary font-weight-bold" style="font-size:4rem">
                        {{ property.formatedPrice }}    €
                    </div>
                    <a href="#" class="btn btn-primary">
                        {% trans %}
                        Contact the agency
                        {% endtrans %}
                    </a>
                    <div class="contactForm" class="mt-4">
                        {{ form_start(contactForm) }}
                        <div class="row">
                            <div class="col">{{form_row(contactForm.firstName)}}</div>
                            <div class="col">{{form_row(contactForm.lastName)}}</div>
                        </div>

                         <div class="row">
                            <div class="col">{{form_row(contactForm.phone)}}</div>
                            <div class="col">{{form_row(contactForm.email)}}</div>
                        </div>
                        {{ form_rest(contactForm) }}
                        <div class="form-group">
                            <button class="btn btn-primary btn-block" formnovalidate>
                                {% trans %}
                                Contact
                                {% endtrans %}
                            </button>
                        </div>
                        {{ form_end(contactForm) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
	<div class="container mt-4">
        <p>
            {{ property.description|nl2br }}
        </p>

        <div class="row">
			<div class="col-md-8">
                <h2> {% trans %} Features {% endtrans %} </h2>
                <table class="table table-striped table-hovered mb-0">
                    <thead>
                        <tr>
                            <th class="text-center text-uppercase">
                                {% trans %} Livable surface {% endtrans %} 
                            </th> 
                            <th class="text-center text-uppercase">
                                {% trans %} Number of pieces {% endtrans %} 
                            </th>   
                            <th class="text-center text-uppercase">
                                {% trans %} Number of rooms {% endtrans %} 
                            </th>
                            <th class="text-center text-uppercase">
                                {% trans %} Floor {% endtrans %} 
                            </th>
                            <th class="text-center text-uppercase"> 
                                {% trans %} Type of heating {% endtrans %} 
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="text-center align-middle">
                                {{property.surface}}
                            </td> 
                            <td class="text-center align-middle">
                                {{property.rooms}}
                            </th>   
                            <th class="text-center align-middle">
                                {{property.bedrooms}}
                            </th>
                            <th class="text-center align-middle">
                                {{property.floor}}
                            </th>
                            <th class="text-center align-middle"> 
                                {{property.heatType }}
                            </th>
                        </tr>
                    </tbody>
                </table>
            </div>

			<div class="col-md-4">
				<h2> {% trans %} Specificities {% endtrans %} </h2>
                <ul class="list-group">
                    {% for option in property.options %}
                        <li class="list-group-item">{{option.name}}</li>
                    {% else %}
                        <p>{% trans %} No specificities {% endtrans %}</p>
                    {% endfor %}
                </ul>
			</div>
		</div>
       
	</div>
{% endblock %}